### ISSUE TITLE
Crash while placing a machine on Dedicated Server only

### ISSUE THREAD

**Issue by Faeranne** [Frinn38/Custom-Machinery#21]
Custom Machinery Version: 0.4.2
Forge Version: 1.6.5-36.2.0
Error Log: https://pastebin.com/hGwvpPDk

Steps to reproduce:
1. Launch dedicated server with Forge 36.2.0 and CM 0.4.2
2. Load Test datapack
3. Log in and /reload
4. Attempt to place any machine

What's Expected:
Machine should be placed in the world.

What happened:
Game crashed with error.

Snippet for easy searching:
```
java.lang.NoSuchMethodError: net.minecraft.util.ResourceLocation.func_217855_b(Ljava/lang/String;)Z
	at fr.frinn.custommachinery.common.init.CustomMachineItem.getMachine(CustomMachineItem.java:34) ~[custommachinery:1.16.5-0.4.2] {re:classloading}
	at fr.frinn.custommachinery.common.init.CustomMachineItem.func_195943_a(CustomMachineItem.java:53) ~[custommachinery:1.16.5-0.4.2] {re:classloading}
	at net.minecraft.item.BlockItem.func_195942_a(BlockItem.java:65) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.item.BlockItem.func_195939_a(BlockItem.java:39) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:644) ~[forge:?] {re:classloading}
	at net.minecraft.item.ItemStack.func_196084_a(ItemStack.java:187) ~[?:?] 
```

**Comment by Frinn38** [comment]
Fixed in 0.4.3
