### ISSUE TITLE
forge-1.16.5-36.2.2-server test_datapack

### ISSUE THREAD

**Issue by MarilynPalmer** [Frinn38/Custom-Machinery#22]
[01八月2021 08:44:15.788] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]
Caused by: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: com/ibm/icu/impl/Pair
	at fr.frinn.custommachinery.common.util.Utils.getModifiersForTile(Utils.java:103) ~[custommachinery:1.16.5-0.4.3]
	at fr.frinn.custommachinery.common.crafting.CraftingContext.refreshModifiers(CraftingContext.java:27) ~[custommachinery:1.16.5-0.4.3]
	at fr.frinn.custommachinery.common.crafting.CraftingContext.<init>(CraftingContext.java:23) ~[custommachinery:1.16.5-0.4.3]
	at fr.frinn.custommachinery.common.crafting.CraftingManager.tick(CraftingManager.java:61) ~[custommachinery:1.16.5-0.4.3]
	at fr.frinn.custommachinery.common.init.CustomMachineTile.func_73660_a(CustomMachineTile.java:101) ~[custommachinery:1.16.5-0.4.3]
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
	... 5 more
Caused by: java.lang.NoClassDefFoundError: com/ibm/icu/impl/Pair
	at fr.frinn.custommachinery.common.util.Utils.getModifiersForTile(Utils.java:103) ~[custommachinery:1.16.5-0.4.3]
	at fr.frinn.custommachinery.common.crafting.CraftingContext.refreshModifiers(CraftingContext.java:27) ~[custommachinery:1.16.5-0.4.3]
	at fr.frinn.custommachinery.common.crafting.CraftingContext.<init>(CraftingContext.java:23) ~[custommachinery:1.16.5-0.4.3]
	at fr.frinn.custommachinery.common.crafting.CraftingManager.tick(CraftingManager.java:61) ~[custommachinery:1.16.5-0.4.3]
	at fr.frinn.custommachinery.common.init.CustomMachineTile.func_73660_a(CustomMachineTile.java:101) ~[custommachinery:1.16.5-0.4.3]
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
	... 5 more
Caused by: java.lang.ClassNotFoundException: com.ibm.icu.impl.Pair
	at java.lang.ClassLoader.findClass(Unknown Source) ~[?:1.8.0_301]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:94) ~[modlauncher-8.0.9.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301]
	at fr.frinn.custommachinery.common.util.Utils.getModifiersForTile(Utils.java:103) ~[custommachinery:1.16.5-0.4.3]
	at fr.frinn.custommachinery.common.crafting.CraftingContext.refreshModifiers(CraftingContext.java:27) ~[custommachinery:1.16.5-0.4.3]
	at fr.frinn.custommachinery.common.crafting.CraftingContext.<init>(CraftingContext.java:23) ~[custommachinery:1.16.5-0.4.3]
	at fr.frinn.custommachinery.common.crafting.CraftingManager.tick(CraftingManager.java:61) ~[custommachinery:1.16.5-0.4.3]
	at fr.frinn.custommachinery.common.init.CustomMachineTile.func_73660_a(CustomMachineTile.java:101) ~[custommachinery:1.16.5-0.4.3]
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
	... 5 more

**Comment by Frinn38** [comment]
Should be fixed in the next update.

**Comment by Frinn38** [comment]
Fixed in 0.4.4
